// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gtzojwabugsvnrypyqqt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd0em9qd2FidWdzdm5yeXB5cXF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyNjkwOTksImV4cCI6MjA2Njg0NTA5OX0.Znv_W6ErLUOiU5o7DFFGsoZmS_fOQ46gHhMAWnXXYfU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});